/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stupidevautour;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Bertrand
 */
public class TourJoueurReel extends javax.swing.JPanel {
    FenetrePrincipale fen;
    Joueur joueur;
    ArrayList<JButton> boutonsCartes;
    /**
     * Creates new form TourJoueurReel
     * @param fen
     * @param joueur
     */
    public TourJoueurReel(FenetrePrincipale fen, Joueur joueur) {
        this.fen = fen;
        this.joueur = joueur;
        initComponents();
        initialiser();
    }
    
    private void initialiser()
    {
        boutonsCartes = new ArrayList();
        for(CarteNumero carteNum : joueur.getCartesJeu())
            boutonsCartes.add(new JButton(Integer.toString(carteNum.getValeur())));
        
        
        if(joueur instanceof JoueurReel)
        {
            
            panelCouleurJoueur = new JPanel(new GridBagLayout());
            panelCouleurJoueur.setBackground(joueur.couleur);
            GridBagConstraints c = new GridBagConstraints();
            c.gridy=0;
            for(int i=0; i<boutonsCartes.size(); i++)
            {
                System.out.println("a");
                c.gridx = i;
                panelCouleurJoueur.add(boutonsCartes.get(i), c);
            }
            panelCouleurJoueur.revalidate(); 
            panelCouleurJoueur.repaint();
                
        }
        else
        {
            panelCouleurJoueur.setBackground(joueur.couleur);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCouleurJoueur = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 102, 0));

        javax.swing.GroupLayout panelCouleurJoueurLayout = new javax.swing.GroupLayout(panelCouleurJoueur);
        panelCouleurJoueur.setLayout(panelCouleurJoueurLayout);
        panelCouleurJoueurLayout.setHorizontalGroup(
            panelCouleurJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 909, Short.MAX_VALUE)
        );
        panelCouleurJoueurLayout.setVerticalGroup(
            panelCouleurJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCouleurJoueur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 293, Short.MAX_VALUE)
                .addComponent(panelCouleurJoueur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelCouleurJoueur;
    // End of variables declaration//GEN-END:variables
}
