/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stupidevautour;

import java.io.IOException;

/**
 *
 * @author Bertrand
 */
public class TourIA extends javax.swing.JPanel {
    Joueur joueur;
    /**
     * Creates new form TourIA
     * @param joueur
     */
    public TourIA(Joueur joueur) throws IOException {
        this.joueur = joueur;
        initComponents();
        initialiser();
    }
    
    private void initialiser() throws IOException
    {
        labJoueur.setText(" L'IA "+joueur.getNumero()+" est en train de joueur !");
       /* 
        int i=0
        joueurs 2 = joueurs
        while joueurs2 pas vide
                for(joueurs)
                    tire joueur max -> max SI il est dans joueurs2
                out(i+": "+joueur max)
                joueurs2. remove(joueurmax)*/
        
    }
    
    private TourJoueur jeu() throws IOException
    {
        return joueur.jeu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labJoueur = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 102, 0));

        labJoueur.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labJoueur.setForeground(new java.awt.Color(240, 240, 240));
        labJoueur.setText("Joueur");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labJoueur, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 540, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 271, Short.MAX_VALUE)
                .addComponent(labJoueur))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labJoueur;
    // End of variables declaration//GEN-END:variables
}
